"""
Matthew Yungbluth
Project Euler Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

import time
import math

def main():
    start = time.time()
    pentnums = []
    count = 1
    while count < 3000:
        pentnums.append(int(count*(3*count-1)/2))
        count += 1
    print("half")
    for i in range(len(pentnums)):
        if pentnums[i] == pentnums[len(pentnums)//2]:
            print("halftwo")
        for j in range(i, len(pentnums)):
            if (pentnums[i] + pentnums[j]) in pentnums:
                if abs(pentnums[i] - pentnums[j]) in pentnums:
                    print(abs(pentnums[i] - pentnums[j]), time.time()-start)

main()
